### ISSUE TITLE
make route use https instead of http

### ISSUE THREAD

**Issue by izapolsk** [RonnyPfannschmidt-RedHat/devpi-cloud-deployments#4]

**Comment by quarckster** [comment]
Fixed in #8

**Comment by RonnyPfannschmidt** [comment]
closing as per comment

**Comment by izapolsk** [comment]
have I missed something ?  afaik I already fixed it some time ago. I just forgot to close this ticket.

**Comment by RonnyPfannschmidt** [comment]
this might be a misunderstanding to the order of things
